apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: ${CLUSTER_CA}
    server: ${CLUSTER_SERVER}
  name: ${CLUSTER_NAME}
contexts:
- context:
    cluster: ${CLUSTER_NAME}
    namespace: limited-ns
    user: limited-user
  name: limited-context
current-context: limited-context
users:
- name: limited-user
  user:
    token: ${USER_TOKEN}